name: Psychic
author: LLLinear
version: 1.0.0
api-version: 1.20
main: com.github.lllinear.psychic.Psychic

permissions:
  lllinear.command:
    children:
      psychic:
        default: op
        description: permission to use job command.

commands:
  psychic:
    permission: lllinear.command.psychic
    description: Psychic command.
    permission-message: You don't have enough permission to use this command.
